[package]
name = "terrarium_controller"
version = "0.1.0"
edition = "2021"
authors = ["Michael Schnieders"]

[dependencies]
tokio = { version = "1", features = ["full"] }									#
serde = { version = "1.0", features = ["derive"] }								#
chrono = { version = "0.4", features = ["serde"] }								#
toml = "0.7"																	# 
axum = "0.6"                                  									# Web framework
sqlx = { version = "0.8.2", features = ["sqlite", "runtime-tokio-native-tls"] } # SQLite database
tower = "0.4"                                 									# Middleware and routing
rppal = "0.13"																	# GPIO
dht-sensor = "0.2.1"															#
rusqlite = { version = "0.29", features = ["bundled"] }							# sqlite db
embedded-hal = { version = "0.2.7", features = ["unproven"] }					#

[[bin]]
name = "terra-control"
path = "main.rs"