[main]
setup_mode = true

[get_data]
retry = 3 
interval = 60
backup_sensor = true
storage_days = 30
ds18b20_bus = 4
dht22_pin = 18

[light_control]
overheat_temp = 50
overheat_time = 3000

[gpio]
led_relay = 17
uv_relay1 = 22
uv_relay2 = 23
heat_relay = 27
led_relay = 17
ic_count = 16
ds18b20_bus = 4
dht22_pin = 18

[led]
default_mode = "natural"
default_brightness = 50
season_weight = 0.3
fade_duration = 300  # Duration in seconds for fade in/out
fade_steps = 60     # Number of steps for smooth fading

# Natural light presets
[morning]
r = 255
g = 180
b = 100
ww = 200
cw = 50

[noon]
r = 255
g = 240
b = 220
ww = 50
cw = 255

[evening]
r = 255
g = 140
b = 50
ww = 255
cw = 0

[web]
address = "0.0.0.0"
port = 80

[db]
def_uv1_start = "06:30"
def_uv1_end = "19:00"
def_uv2_start = "07:00"
def_uv2_end = "19:30"
def_heat_start = "10:00"
def_heat_end = "14:30"
def_led_R = 150
def_led_G = 150
def_led_B = 128
def_led_WW = 128
def_led_CW = 128